# Generated by Django 2.1.7 on 2019-04-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateField(verbose_name='Date Added')),
            ],
        ),
        migrations.CreateModel(
            name='StockPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('value_per_share', models.FloatField(verbose_name='Value per share')),
                ('date_added', models.DateField(verbose_name='Date Added')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Portfolio')),
            ],
        ),
    ]
