# Generated by Django 2.1.7 on 2019-04-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockpick',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stockpick',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='stockpick',
            name='url',
        ),
        migrations.AddField(
            model_name='stockpick',
            name='stock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portfolio_app.Stock'),
            preserve_default=False,
        ),
    ]
