# Generated by Django 2.2 on 2019-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20190402_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='stockpick',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Added'),
        ),
    ]
